Fix RuntimeError in puddleobjects.py by swallowing StopIteration exception
Traceback (most recent call last):
  File "/home/user/.data/miniconda3/envs/puddletag/lib/python3.12/site-packages/puddlestuff/puddleobjects.py", line 657, in getfiles
    dirname, subs, fnames = next(os.walk(f))
                            ^^^^^^^^^^^^^^^^
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.data/miniconda3/envs/puddletag/lib/python3.12/site-packages/puddlestuff/puddleobjects.py", line 2418, in run
    self.retval = self.command()
                  ^^^^^^^^^^^^^^
  File "/home/user/.data/miniconda3/envs/puddletag/lib/python3.12/site-packages/puddlestuff/puddleobjects.py", line 875, in threadfunc
    temp = next(f)
           ^^^^^^^
  File "/home/user/.data/miniconda3/envs/puddletag/lib/python3.12/site-packages/puddlestuff/tagmodel.py", line 1905, in load_dir
    for fname in getfiles(dirs, subfolders):
RuntimeError: generator raised StopIteration